services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - redis
    # restart: unless-stopped
    
    
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6739:6739"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
