services:
  api:
    build:
      context: ./app
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
    expose:
      - "8000"
    depends_on:
      - redis
    # restart: unless-stopped
    
    
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6739:6739"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  redis-data:
